# Generated by Django 6.1.1 on 2026-09-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('yape', 'Yape'), ('plin', 'Plin'), ('tarjeta', 'Tarjeta de crédito/débito'), ('transferencia', 'Transferencia bancaria'), ('contraentrega', 'Pago contra entrega')], default='yape', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo_envio',
            field=models.CharField(choices=[('recojo', 'Recojo en tienda (gratis)'), ('delivery_lima', 'Delivery Lima (S/ 10.00)'), ('delivery_provincia', 'Delivery Provincia (S/ 20.00)')], default='recojo', max_length=20),
        ),
    ]
